# permissions for end users to view hikawas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hikawa-viewer-role
rules:
- apiGroups:
  - zundokokiyoshi.kaitoy.github.com
  resources:
  - hikawas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - zundokokiyoshi.kaitoy.github.com
  resources:
  - hikawas/status
  verbs:
  - get
