# permissions for end users to edit hikawas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hikawa-editor-role
rules:
- apiGroups:
  - zundokokiyoshi.kaitoy.github.com
  resources:
  - hikawas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - zundokokiyoshi.kaitoy.github.com
  resources:
  - hikawas/status
  verbs:
  - get
