# permissions for end users to edit kiyoshis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kiyoshi-editor-role
rules:
- apiGroups:
  - zundokokiyoshi.kaitoy.github.com
  resources:
  - kiyoshis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - zundokokiyoshi.kaitoy.github.com
  resources:
  - kiyoshis/status
  verbs:
  - get
