# permissions for end users to edit zundokoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zundoko-editor-role
rules:
- apiGroups:
  - zundokokiyoshi.kaitoy.github.com
  resources:
  - zundokoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - zundokokiyoshi.kaitoy.github.com
  resources:
  - zundokoes/status
  verbs:
  - get
