# permissions for end users to view zundokoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zundoko-viewer-role
rules:
- apiGroups:
  - zundokokiyoshi.kaitoy.github.com
  resources:
  - zundokoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - zundokokiyoshi.kaitoy.github.com
  resources:
  - zundokoes/status
  verbs:
  - get
