---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: hikawas.zundokokiyoshi.kaitoy.github.com
spec:
  group: zundokokiyoshi.kaitoy.github.com
  names:
    kind: Hikawa
    listKind: HikawaList
    plural: hikawas
    singular: hikawa
  scope: Namespaced
  versions:
  - name: v1beta2
    schema:
      openAPIV3Schema:
        description: Hikawa is the Schema for the hikawas API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of Hikawa
            type: object
            properties:
              intervalMillis:
                type: integer
                format: int64
              numZundokos:
                type: string
                pattern: '^\d+$'
              sayKiyoshi:
                type: boolean
            required:
            - intervalMillis
          status:
            description: Status defines the observed state of Hikawa
            properties:
              kiyoshied:
                type: boolean
              numZundokosSaid:
                type: string
                pattern: '^\d+$'
            required:
            - numZundokosSaid
            - kiyoshied
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
